services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  client:
    build:
      context: ./client
      target: "development"
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5555:5555"
    volumes:
      - ./client/app:/usr/server/app
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SESSION_SECRET: ${SESSION_SECRET}
    depends_on:
      - db

  redis:
    image: "redis:latest"
    volumes:
      - ./redis:/data

  django:
    build: django
    ports:
      - "8000:8000"
    volumes:
      - ./public:/public
    environment:
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=True
      - STATIC_HOST=localhost:8080
      - STATIC_PROTOCOL=http
      - DJANGO_HOST=localhost
      - POSTGRES_NAME=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
      - redis

  nginx:
    image: nginx
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./public:/public
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=_
      - NGINX_PORT=80
